apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: githubapp-root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/praveenjayakar/config-sync
    branch: main
    dir: base/nginx/01
    auth: githubapp
    secretRef:
      name: github-creds
